server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml;


    add_header Strict-Transport-Security "max-age=31536000" always;

    location ~* ^/(favicon\.svg|favicon-32\.png|apple-touch-icon\.png|img/|icons/) {
        add_header Strict-Transport-Security "max-age=31536000" always;
        add_header Cache-Control "public, max-age=3600" always;
        try_files $uri =404;
    }

    location ~* \.(js|css|woff2|png|jpg|jpeg|svg|ico|webp)$ {
        add_header Strict-Transport-Security "max-age=31536000" always;
        add_header Cache-Control "public, immutable, max-age=31536000" always;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Strict-Transport-Security "max-age=31536000" always;
        add_header Cache-Control "no-cache";
    }
}
